[package]
name = "runtime"
version = "0.1.0"
authors = ["Emily Herbert <emilyherbert@cs.umass.edu>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "*"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
