[package]
name = "jankscripten"
version = "0.1.0"
authors = ["Arjun Guha <arjun@cs.umass.edu>"]
edition = "2018"

[dependencies]
libjankscripten = { path = "../libjankscripten" }
clap = "3.0.0-beta.1"