[package]
name = "jankyp"
version = "0.1.0"
authors = ["Arjun Guha <arjun@cs.umass.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libjankscripten = { path = "../libjankscripten" }
clap = "3.0.0-beta.1"