[package]
name = "libjankscripten"
version = "0.1.0"
authors = ["Arjun Guha <arjun@cs.umass.edu>"]
edition = "2018"

[dependencies]
ressa = "*"
resast = "*"
thiserror = "*"
pretty = "^0.10.0"
parity-wasm = "^0.41.0"

[dev-dependencies]
rusty_v8 = "^0.4.2"
