name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Build integration testing tool
        working-directory: integration_tests
        run: npm install
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Run unit tests
        run: cargo test --verbose -- --test-threads=1
      - name: Run integration tests
        run: npm run-script test
        working-directory: integration_tests
  fmt:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Check format
      run: cargo fmt -- --check
